import * as path from "node:path";
import { expect, test } from "vitest";
import {
	debugSemanticProgram,
	loadEntrypointAndRunSemanticAnalysis,
} from "../src/semantic-analysis.ts";

test("snapshot sema changes", () => {
	const semantic = loadEntrypointAndRunSemanticAnalysis(
		path.join(import.meta.dirname, "./local/semantic-analysis.js"),
	);

	// TODO: handle local paths for CI runs
	expect(debugSemanticProgram(semantic)).toMatchInlineSnapshot(`
		"/Users/dirk/projects/maligator/tests/local/semantic-analysis.js
		  Scope(0 Program (parent: -1)
		    Binding(assert let global FunctionDeclaration) (usages: 34, declared: true) 
		    Binding(isPrimitive let global FunctionDeclaration) (usages: 3, declared: true) 
		    Binding(compareArray let global FunctionDeclaration) (usages: 4, declared: true) 
		    Binding(Test262Error let global FunctionDeclaration) (usages: 21, declared: true) 
		    Binding($DONOTEVALUATE let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(__isArray var global Identifier) (usages: 2, declared: true) 
		    Binding(__defineProperty var global Identifier) (usages: 2, declared: true) 
		    Binding(__getOwnPropertyDescriptor var global Identifier) (usages: 8, declared: true) 
		    Binding(__getOwnPropertyNames var global Identifier) (usages: 2, declared: true) 
		    Binding(__join var global Identifier) (usages: 2, declared: true) 
		    Binding(__push var global Identifier) (usages: 6, declared: true) 
		    Binding(__hasOwnProperty var global Identifier) (usages: 11, declared: true) 
		    Binding(__propertyIsEnumerable var global Identifier) (usages: 2, declared: true) 
		    Binding(nonIndexNumericPropertyName var global Identifier) (usages: 2, declared: true) 
		    Binding(verifyProperty let global FunctionDeclaration) (usages: 5, declared: true) 
		    Binding(isConfigurable let global FunctionDeclaration) (usages: 4, declared: true) 
		    Binding(isEnumerable let global FunctionDeclaration) (usages: 4, declared: true) 
		    Binding(isSameValue let global FunctionDeclaration) (usages: 5, declared: true) 
		    Binding(isWritable let global FunctionDeclaration) (usages: 4, declared: true) 
		    Binding(verifyCallableProperty let global FunctionDeclaration) (usages: 2, declared: true) 
		    Binding(verifyEqualTo let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(verifyWritable let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(verifyNotWritable let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(verifyEnumerable let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(verifyNotEnumerable let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(verifyConfigurable let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(verifyNotConfigurable let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(verifyPrimordialProperty var global Identifier) (usages: 1, declared: true) 
		    Binding(verifyPrimordialCallableProperty var global Identifier) (usages: 1, declared: true) 
		    Binding(x let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(TestClass let global ClassDeclaration) (usages: 1, declared: true) 
		    Binding(hoistedVar var global Identifier) (usages: 1, declared: true) 
		    Binding(varInNestedBlocks let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(varShadowsParam let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(multipleVarSameName let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(funcVsVar let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(funcInBlock let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(varBeforeFunc let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(outerHoisting let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(varInForIn let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(varInForOf let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(varDestructuring let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(sloppyBlockFunc let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(varInLabeled let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(complexParam let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(usageBeforeDecl let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(catchParamShadow let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(captureCheck let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(someFunction let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(Array var global Identifier) (usages: 3, declared: false) 
		    Binding(Object var global Identifier) (usages: 5, declared: false) 
		    Binding(Function var global Identifier) (usages: 4, declared: false) 
		    Binding(Math var global Identifier) (usages: 1, declared: false) 
		  Scope(1 FunctionDeclaration (parent: 0)
		    Binding(mustBeTrue var local Identifier) (usages: 3, declared: true) 
		    Binding(message var local Identifier) (usages: 4, declared: true) 
		  Scope(2 BlockStatement (parent: 1)
		    Binding(undefined var local Identifier) (usages: 1, declared: false) 
		  Scope(3 BlockStatement (parent: 2)
		  Scope(4 BlockStatement (parent: 2)
		  Scope(5 FunctionExpression (parent: 0)
		    Binding(a var local Identifier) (usages: 6, declared: true) 
		    Binding(b var local Identifier) (usages: 5, declared: true) 
		  Scope(6 BlockStatement (parent: 5)
		  Scope(7 BlockStatement (parent: 6)
		  Scope(8 FunctionExpression (parent: 0)
		    Binding(actual var local Identifier) (usages: 3, declared: true) 
		    Binding(expected var local Identifier) (usages: 3, declared: true) 
		    Binding(message var local Identifier) (usages: 7, declared: true) 
		  Scope(9 BlockStatement (parent: 8)
		    Binding(error let local Identifier) (usages: 2, declared: true) 
		    Binding(undefined var local Identifier) (usages: 1, declared: false) 
		  Scope(10 BlockStatement (parent: 9)
		  Scope(11 BlockStatement (parent: 10)
		  Scope(12 BlockStatement (parent: 9)
		  Scope(13 BlockStatement (parent: 9)
		  Scope(14 BlockStatement (parent: 9)
		  Scope(15 FunctionExpression (parent: 0)
		    Binding(actual var local Identifier) (usages: 3, declared: true) 
		    Binding(unexpected var local Identifier) (usages: 3, declared: true) 
		    Binding(message var local Identifier) (usages: 6, declared: true) 
		  Scope(16 BlockStatement (parent: 15)
		    Binding(undefined var local Identifier) (usages: 1, declared: false) 
		  Scope(17 BlockStatement (parent: 16)
		  Scope(18 BlockStatement (parent: 16)
		  Scope(19 BlockStatement (parent: 16)
		  Scope(20 FunctionExpression (parent: 0)
		    Binding(expectedErrorConstructor var local Identifier) (usages: 4, declared: true) 
		    Binding(func var local Identifier) (usages: 3, declared: true) 
		    Binding(message var local Identifier) (usages: 11, declared: true) 
		  Scope(21 BlockStatement (parent: 20)
		    Binding(expectedName var local Identifier) (usages: 5, declared: true) 
		    Binding(actualName var local Identifier) (usages: 4, declared: true) 
		    Binding(thrown let local Identifier) (usages: 5, declared: true) 
		    Binding(undefined var local Identifier) (usages: 1, declared: false) 
		  Scope(22 BlockStatement (parent: 21)
		  Scope(23 BlockStatement (parent: 21)
		  Scope(24 BlockStatement (parent: 21)
		  Scope(25 BlockStatement (parent: 21)
		  Scope(26 BlockStatement (parent: 21)
		  Scope(27 BlockStatement (parent: 26)
		  Scope(28 BlockStatement (parent: 26)
		  Scope(29 BlockStatement (parent: 28)
		  Scope(30 BlockStatement (parent: 28)
		  Scope(31 FunctionDeclaration (parent: 0)
		    Binding(value var local Identifier) (usages: 4, declared: true) 
		  Scope(32 BlockStatement (parent: 31)
		  Scope(33 FunctionExpression (parent: 0)
		    Binding(actual var local Identifier) (usages: 5, declared: true) 
		    Binding(expected var local Identifier) (usages: 5, declared: true) 
		    Binding(message var local Identifier) (usages: 10, declared: true) 
		  Scope(34 BlockStatement (parent: 33)
		    Binding(result var local Identifier) (usages: 2, declared: true) 
		    Binding(format var local Identifier) (usages: 3, declared: true) 
		    Binding(undefined var local Identifier) (usages: 1, declared: false) 
		  Scope(35 BlockStatement (parent: 34)
		  Scope(36 BlockStatement (parent: 34)
		  Scope(37 BlockStatement (parent: 34)
		  Scope(38 FunctionDeclaration (parent: 0)
		    Binding(a var local Identifier) (usages: 4, declared: true) 
		    Binding(b var local Identifier) (usages: 3, declared: true) 
		  Scope(39 BlockStatement (parent: 38)
		    Binding(i var local Identifier) (usages: 5, declared: true) 
		  Scope(40 BlockStatement (parent: 39)
		  Scope(41 ForStatement (parent: 39)
		  Scope(42 BlockStatement (parent: 41)
		  Scope(43 BlockStatement (parent: 42)
		  Scope(44 FunctionExpression (parent: 0)
		    Binding(arrayLike var local Identifier) (usages: 2, declared: true) 
		  Scope(45 BlockStatement (parent: 44)
		    Binding(Array var local Identifier) (usages: 1, declared: false) 
		    Binding(String var local Identifier) (usages: 1, declared: false) 
		  Scope(46 FunctionExpression (parent: 0)
		    Binding(formatIdentityFreeValue let local FunctionExpression) (usages: 1, declared: true) 
		    Binding(value var local Identifier) (usages: 9, declared: true) 
		  Scope(47 BlockStatement (parent: 46)
		  Scope(48 SwitchStatement (parent: 47)
		    Binding(JSON var local Identifier) (usages: 2, declared: false) 
		    Binding(Infinity var local Identifier) (usages: 1, declared: false) 
		    Binding(String var local Identifier) (usages: 1, declared: false) 
		  Scope(49 FunctionExpression (parent: 0)
		    Binding(value var local Identifier) (usages: 4, declared: true) 
		  Scope(50 BlockStatement (parent: 49)
		    Binding(basic var local Identifier) (usages: 3, declared: true) 
		    Binding(err let local Identifier) (usages: 3, declared: true) 
		  Scope(51 BlockStatement (parent: 50)
		    Binding(String var local Identifier) (usages: 1, declared: false) 
		  Scope(52 BlockStatement (parent: 50)
		  Scope(53 BlockStatement (parent: 52)
		    Binding(Object var local Identifier) (usages: 1, declared: false) 
		  Scope(54 FunctionDeclaration (parent: 0)
		    Binding(message var local Identifier) (usages: 2, declared: true) 
		  Scope(55 BlockStatement (parent: 54)
		  Scope(56 FunctionExpression (parent: 0)
		  Scope(57 BlockStatement (parent: 56)
		  Scope(58 FunctionExpression (parent: 0)
		    Binding(message var local Identifier) (usages: 2, declared: true) 
		  Scope(59 BlockStatement (parent: 58)
		  Scope(60 FunctionDeclaration (parent: 0)
		  Scope(61 BlockStatement (parent: 60)
		  Scope(62 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 8, declared: true) 
		    Binding(name var local Identifier) (usages: 9, declared: true) 
		    Binding(desc var local Identifier) (usages: 26, declared: true) 
		    Binding(options var local Identifier) (usages: 3, declared: true) 
		    Binding(arguments var local FunctionDeclaration) (usages: 1, declared: true) 
		  Scope(63 BlockStatement (parent: 62)
		    Binding(originalDesc var local Identifier) (usages: 7, declared: true) 
		    Binding(nameStr var local Identifier) (usages: 8, declared: true) 
		    Binding(names var local Identifier) (usages: 9, declared: true) 
		    Binding(i var local Identifier) (usages: 10, declared: true) 
		    Binding(failures var local Identifier) (usages: 8, declared: true) 
		    Binding(String var local Identifier) (usages: 2, declared: false) 
		    Binding(undefined var local Identifier) (usages: 5, declared: false) 
		  Scope(64 BlockStatement (parent: 63)
		  Scope(65 ForStatement (parent: 63)
		  Scope(66 BlockStatement (parent: 65)
		  Scope(67 BlockStatement (parent: 63)
		  Scope(68 BlockStatement (parent: 67)
		  Scope(69 BlockStatement (parent: 67)
		  Scope(70 BlockStatement (parent: 63)
		  Scope(71 BlockStatement (parent: 70)
		  Scope(72 BlockStatement (parent: 63)
		  Scope(73 BlockStatement (parent: 72)
		  Scope(74 BlockStatement (parent: 63)
		  Scope(75 BlockStatement (parent: 74)
		  Scope(76 BlockStatement (parent: 63)
		  Scope(77 BlockStatement (parent: 63)
		  Scope(78 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 3, declared: true) 
		    Binding(name var local Identifier) (usages: 3, declared: true) 
		  Scope(79 BlockStatement (parent: 78)
		    Binding(e let local Identifier) (usages: 3, declared: true) 
		  Scope(80 BlockStatement (parent: 79)
		  Scope(81 BlockStatement (parent: 79)
		    Binding(TypeError var local Identifier) (usages: 1, declared: false) 
		  Scope(82 BlockStatement (parent: 81)
		  Scope(83 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 4, declared: true) 
		    Binding(name var local Identifier) (usages: 5, declared: true) 
		  Scope(84 BlockStatement (parent: 83)
		    Binding(stringCheck var local Identifier) (usages: 4, declared: true) 
		    Binding(x var local Identifier) (usages: 2, declared: true) 
		  Scope(85 BlockStatement (parent: 84)
		  Scope(86 ForInStatement (parent: 85)
		  Scope(87 BlockStatement (parent: 86)
		  Scope(88 BlockStatement (parent: 87)
		  Scope(89 BlockStatement (parent: 84)
		  Scope(90 FunctionDeclaration (parent: 0)
		    Binding(a var local Identifier) (usages: 6, declared: true) 
		    Binding(b var local Identifier) (usages: 6, declared: true) 
		  Scope(91 BlockStatement (parent: 90)
		  Scope(92 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 8, declared: true) 
		    Binding(name var local Identifier) (usages: 8, declared: true) 
		    Binding(verifyProp var local Identifier) (usages: 2, declared: true) 
		    Binding(value var local Identifier) (usages: 2, declared: true) 
		    Binding(arguments var local FunctionDeclaration) (usages: 1, declared: true) 
		  Scope(93 BlockStatement (parent: 92)
		    Binding(unlikelyValue var local Identifier) (usages: 2, declared: true) 
		    Binding(newValue var local Identifier) (usages: 6, declared: true) 
		    Binding(hadValue var local Identifier) (usages: 2, declared: true) 
		    Binding(oldValue var local Identifier) (usages: 3, declared: true) 
		    Binding(writeSucceeded var local Identifier) (usages: 4, declared: true) 
		    Binding(e let local Identifier) (usages: 3, declared: true) 
		  Scope(94 BlockStatement (parent: 93)
		  Scope(95 BlockStatement (parent: 93)
		  Scope(96 BlockStatement (parent: 93)
		    Binding(TypeError var local Identifier) (usages: 1, declared: false) 
		  Scope(97 BlockStatement (parent: 96)
		  Scope(98 BlockStatement (parent: 93)
		  Scope(99 BlockStatement (parent: 98)
		  Scope(100 BlockStatement (parent: 98)
		  Scope(101 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 3, declared: true) 
		    Binding(name var local Identifier) (usages: 7, declared: true) 
		    Binding(functionName var local Identifier) (usages: 5, declared: true) 
		    Binding(functionLength var local Identifier) (usages: 2, declared: true) 
		    Binding(desc var local Identifier) (usages: 9, declared: true) 
		    Binding(options var local Identifier) (usages: 4, declared: true) 
		  Scope(102 BlockStatement (parent: 101)
		    Binding(value var local Identifier) (usages: 9, declared: true) 
		    Binding(String var local Identifier) (usages: 1, declared: false) 
		    Binding(undefined var local Identifier) (usages: 2, declared: false) 
		    Binding(writable var local Identifier) (usages: 2, declared: false) 
		    Binding(enumerable var local Identifier) (usages: 2, declared: false) 
		    Binding(configurable var local Identifier) (usages: 2, declared: false) 
		  Scope(103 BlockStatement (parent: 102)
		    Binding(writable var local Identifier) (usages: 1, declared: false) 
		    Binding(enumerable var local Identifier) (usages: 1, declared: false) 
		    Binding(configurable var local Identifier) (usages: 1, declared: false) 
		  Scope(104 BlockStatement (parent: 102)
		  Scope(105 BlockStatement (parent: 102)
		  Scope(106 BlockStatement (parent: 105)
		  Scope(107 BlockStatement (parent: 105)
		  Scope(108 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 3, declared: true) 
		    Binding(name var local Identifier) (usages: 4, declared: true) 
		    Binding(value var local Identifier) (usages: 3, declared: true) 
		  Scope(109 BlockStatement (parent: 108)
		  Scope(110 BlockStatement (parent: 109)
		    Binding(String var local Identifier) (usages: 1, declared: false) 
		  Scope(111 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 3, declared: true) 
		    Binding(name var local Identifier) (usages: 5, declared: true) 
		    Binding(verifyProp var local Identifier) (usages: 3, declared: true) 
		    Binding(value var local Identifier) (usages: 2, declared: true) 
		  Scope(112 BlockStatement (parent: 111)
		  Scope(113 BlockStatement (parent: 112)
		    Binding(String var local Identifier) (usages: 1, declared: false) 
		  Scope(114 BlockStatement (parent: 112)
		    Binding(String var local Identifier) (usages: 1, declared: false) 
		  Scope(115 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 3, declared: true) 
		    Binding(name var local Identifier) (usages: 5, declared: true) 
		    Binding(verifyProp var local Identifier) (usages: 3, declared: true) 
		    Binding(value var local Identifier) (usages: 1, declared: true) 
		  Scope(116 BlockStatement (parent: 115)
		  Scope(117 BlockStatement (parent: 116)
		    Binding(String var local Identifier) (usages: 1, declared: false) 
		  Scope(118 BlockStatement (parent: 116)
		    Binding(String var local Identifier) (usages: 1, declared: false) 
		  Scope(119 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 3, declared: true) 
		    Binding(name var local Identifier) (usages: 5, declared: true) 
		  Scope(120 BlockStatement (parent: 119)
		    Binding(String var local Identifier) (usages: 2, declared: false) 
		  Scope(121 BlockStatement (parent: 120)
		  Scope(122 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 3, declared: true) 
		    Binding(name var local Identifier) (usages: 5, declared: true) 
		  Scope(123 BlockStatement (parent: 122)
		    Binding(String var local Identifier) (usages: 2, declared: false) 
		  Scope(124 BlockStatement (parent: 123)
		  Scope(125 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 3, declared: true) 
		    Binding(name var local Identifier) (usages: 5, declared: true) 
		  Scope(126 BlockStatement (parent: 125)
		    Binding(String var local Identifier) (usages: 2, declared: false) 
		  Scope(127 BlockStatement (parent: 126)
		  Scope(128 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 3, declared: true) 
		    Binding(name var local Identifier) (usages: 5, declared: true) 
		  Scope(129 BlockStatement (parent: 128)
		    Binding(String var local Identifier) (usages: 2, declared: false) 
		  Scope(130 BlockStatement (parent: 129)
		  Scope(131 FunctionDeclaration (parent: 0)
		    Binding(quix var local ObjectPattern) (usages: 2, declared: true) 
		  Scope(132 BlockStatement (parent: 131)
		    Binding(y let captured FunctionDeclaration) (usages: 1, declared: true) 
		  Scope(133 FunctionDeclaration (parent: 132)
		    Binding(arg var local Identifier) (usages: 1, declared: true) 
		  Scope(134 BlockStatement (parent: 133)
		  Scope(135 ClassDeclaration (parent: 0)
		    Binding(staticField var local Identifier) (usages: 1, declared: false) 
		    Binding(publicField var local Identifier) (usages: 1, declared: false) 
		    Binding(constructor var local Identifier) (usages: 1, declared: false) 
		    Binding(value var local Identifier) (usages: 2, declared: false) 
		    Binding(methodWithVar var local Identifier) (usages: 1, declared: false) 
		  Scope(136 FunctionExpression (parent: 135)
		    Binding(name var local Identifier) (usages: 2, declared: true) 
		  Scope(137 BlockStatement (parent: 136)
		  Scope(138 FunctionExpression (parent: 135)
		  Scope(139 BlockStatement (parent: 138)
		  Scope(140 FunctionExpression (parent: 135)
		  Scope(141 BlockStatement (parent: 140)
		  Scope(142 FunctionExpression (parent: 135)
		    Binding(v var local Identifier) (usages: 2, declared: true) 
		  Scope(143 BlockStatement (parent: 142)
		  Scope(144 StaticBlock (parent: 135)
		    Binding(blockScoped let local Identifier) (usages: 1, declared: true) 
		  Scope(145 FunctionExpression (parent: 135)
		  Scope(146 BlockStatement (parent: 145)
		    Binding(functionScoped var local Identifier) (usages: 2, declared: true) 
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		  Scope(147 BlockStatement (parent: 146)
		    Binding(blockScoped let local Identifier) (usages: 1, declared: true) 
		  Scope(148 FunctionDeclaration (parent: 0)
		  Scope(149 BlockStatement (parent: 148)
		    Binding(hoistedFromIf var local Identifier) (usages: 2, declared: true) 
		    Binding(hoistedFromWhile var local Identifier) (usages: 2, declared: true) 
		    Binding(hoistedFromSwitch var local Identifier) (usages: 2, declared: true) 
		    Binding(hoistedFromTry var local Identifier) (usages: 1, declared: true) 
		    Binding(e let local Identifier) (usages: 1, declared: true) 
		    Binding(hoistedFromCatch var local Identifier) (usages: 1, declared: true) 
		    Binding(hoistedFromFinally var local Identifier) (usages: 1, declared: true) 
		    Binding(i var local Identifier) (usages: 3, declared: true) 
		    Binding(hoistedFromFor var local Identifier) (usages: 1, declared: true) 
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		  Scope(150 BlockStatement (parent: 149)
		  Scope(151 BlockStatement (parent: 149)
		  Scope(152 SwitchStatement (parent: 149)
		  Scope(153 BlockStatement (parent: 149)
		  Scope(154 BlockStatement (parent: 149)
		  Scope(155 BlockStatement (parent: 149)
		  Scope(156 ForStatement (parent: 149)
		  Scope(157 BlockStatement (parent: 156)
		  Scope(158 FunctionDeclaration (parent: 0)
		    Binding(param1 var local Identifier) (usages: 1, declared: true) 
		    Binding(param2 var local Identifier) (usages: 1, declared: true) 
		  Scope(159 BlockStatement (parent: 158)
		    Binding(param1 var local Identifier) (usages: 2, declared: true) 
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		  Scope(160 FunctionDeclaration (parent: 0)
		  Scope(161 BlockStatement (parent: 160)
		    Binding(x var local Identifier) (usages: 3, declared: true) 
		    Binding(x var local Identifier) (usages: 0, declared: true) 
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		  Scope(162 BlockStatement (parent: 161)
		  Scope(163 FunctionDeclaration (parent: 0)
		  Scope(164 BlockStatement (parent: 163)
		    Binding(innerFunc var captured Identifier) (usages: 3, declared: true) 
		    Binding(innerFunc let local FunctionDeclaration) (usages: 0, declared: true) 
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		  Scope(165 FunctionDeclaration (parent: 164)
		  Scope(166 BlockStatement (parent: 165)
		  Scope(167 FunctionDeclaration (parent: 0)
		  Scope(168 BlockStatement (parent: 167)
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		    Binding(blockFunc var local Identifier) (usages: 1, declared: false) 
		  Scope(169 BlockStatement (parent: 168)
		    Binding(blockFunc let captured FunctionDeclaration) (usages: 1, declared: true) 
		  Scope(170 FunctionDeclaration (parent: 169)
		  Scope(171 BlockStatement (parent: 170)
		  Scope(172 FunctionDeclaration (parent: 0)
		  Scope(173 BlockStatement (parent: 172)
		    Binding(sameName var captured Identifier) (usages: 3, declared: true) 
		    Binding(sameName let local FunctionDeclaration) (usages: 0, declared: true) 
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		  Scope(174 FunctionDeclaration (parent: 173)
		  Scope(175 BlockStatement (parent: 174)
		  Scope(176 FunctionDeclaration (parent: 0)
		  Scope(177 BlockStatement (parent: 176)
		    Binding(innerFn let captured FunctionDeclaration) (usages: 2, declared: true) 
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		  Scope(178 FunctionDeclaration (parent: 177)
		  Scope(179 BlockStatement (parent: 178)
		  Scope(180 BlockStatement (parent: 177)
		    Binding(nestedBlock let captured FunctionDeclaration) (usages: 1, declared: true) 
		  Scope(181 FunctionDeclaration (parent: 180)
		  Scope(182 BlockStatement (parent: 181)
		  Scope(183 FunctionDeclaration (parent: 0)
		  Scope(184 BlockStatement (parent: 183)
		    Binding(key var local Identifier) (usages: 3, declared: true) 
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		  Scope(185 ForInStatement (parent: 184)
		    Binding(a var local Identifier) (usages: 1, declared: false) 
		  Scope(186 BlockStatement (parent: 185)
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		  Scope(187 FunctionDeclaration (parent: 0)
		  Scope(188 BlockStatement (parent: 187)
		    Binding(item var local Identifier) (usages: 3, declared: true) 
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		  Scope(189 ForOfStatement (parent: 188)
		  Scope(190 BlockStatement (parent: 189)
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		  Scope(191 FunctionDeclaration (parent: 0)
		  Scope(192 BlockStatement (parent: 191)
		    Binding(a var local ObjectPattern) (usages: 4, declared: true) 
		    Binding(renamed var local ObjectPattern) (usages: 2, declared: true) 
		    Binding(first var local ArrayPattern) (usages: 2, declared: true) 
		    Binding(second var local ArrayPattern) (usages: 2, declared: true) 
		    Binding(b var local Identifier) (usages: 2, declared: false) 
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		  Scope(193 FunctionDeclaration (parent: 0)
		  Scope(194 BlockStatement (parent: 193)
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		    Binding(blockHoisted var local Identifier) (usages: 1, declared: false) 
		  Scope(195 BlockStatement (parent: 194)
		    Binding(blockHoisted let captured FunctionDeclaration) (usages: 1, declared: true) 
		  Scope(196 FunctionDeclaration (parent: 195)
		  Scope(197 BlockStatement (parent: 196)
		  Scope(198 FunctionDeclaration (parent: 0)
		  Scope(199 BlockStatement (parent: 198)
		    Binding(i var local Identifier) (usages: 5, declared: true) 
		    Binding(j var local Identifier) (usages: 5, declared: true) 
		    Binding(outer var local Identifier) (usages: 2, declared: false) 
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		  Scope(200 ForStatement (parent: 199)
		  Scope(201 BlockStatement (parent: 200)
		    Binding(inner var local Identifier) (usages: 1, declared: false) 
		  Scope(202 ForStatement (parent: 201)
		  Scope(203 BlockStatement (parent: 202)
		  Scope(204 FunctionDeclaration (parent: 0)
		    Binding(defaultParam var local AssignmentPattern) (usages: 1, declared: true) 
		  Scope(205 FunctionExpression (parent: 204)
		  Scope(206 BlockStatement (parent: 205)
		    Binding(inDefault var local Identifier) (usages: 2, declared: true) 
		  Scope(207 BlockStatement (parent: 204)
		    Binding(inDefault var local Identifier) (usages: 2, declared: true) 
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		  Scope(208 FunctionDeclaration (parent: 0)
		  Scope(209 BlockStatement (parent: 208)
		    Binding(helper let captured FunctionDeclaration) (usages: 2, declared: true) 
		  Scope(210 FunctionDeclaration (parent: 209)
		  Scope(211 BlockStatement (parent: 210)
		  Scope(212 FunctionDeclaration (parent: 0)
		  Scope(213 BlockStatement (parent: 212)
		    Binding(e let local Identifier) (usages: 3, declared: true) 
		    Binding(e var local Identifier) (usages: 0, declared: true) 
		  Scope(214 BlockStatement (parent: 213)
		    Binding(Error var local Identifier) (usages: 1, declared: false) 
		  Scope(215 BlockStatement (parent: 213)
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		  Scope(216 FunctionDeclaration (parent: 0)
		  Scope(217 BlockStatement (parent: 216)
		    Binding(captured let captured Identifier) (usages: 2, declared: true) 
		  Scope(218 FunctionExpression (parent: 217)
		  Scope(219 BlockStatement (parent: 218)
		  Scope(220 FunctionDeclaration (parent: 0)
		    Binding(x var local ObjectPattern) (usages: 7, declared: true) 
		    Binding(y var local ObjectPattern) (usages: 4, declared: true) 
		  Scope(221 BlockStatement (parent: 220)
		  Scope(222 BlockStatement (parent: 221)
		    Binding(result const local Identifier) (usages: 2, declared: true) 
		"
	`);
});
