import * as path from "node:path";
import { expect, test } from "vitest";
import {
	debugSemanticProgram,
	loadEntrypointAndRunSemanticAnalysis,
} from "../src/semantic-analysis.ts";

test("snapshot sema changes", () => {
	const semantic = loadEntrypointAndRunSemanticAnalysis(
		path.join(import.meta.dirname, "./local/semantic-analysis.js"),
	);

	// TODO: handle local paths for CI runs
	expect(debugSemanticProgram(semantic)).toMatchInlineSnapshot(`
		"/Users/dirk/projects/maligator/tests/local/semantic-analysis.js
		  Scope(0 Program (parent: -1)
		    Binding(assert let global FunctionDeclaration) (usages: 34, declared: true) 
		    Binding(isPrimitive let global FunctionDeclaration) (usages: 3, declared: true) 
		    Binding(compareArray let global FunctionDeclaration) (usages: 4, declared: true) 
		    Binding(Test262Error let global FunctionDeclaration) (usages: 21, declared: true) 
		    Binding($DONOTEVALUATE let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(__isArray var global Identifier) (usages: 2, declared: true) 
		    Binding(__defineProperty var global Identifier) (usages: 2, declared: true) 
		    Binding(__getOwnPropertyDescriptor var global Identifier) (usages: 8, declared: true) 
		    Binding(__getOwnPropertyNames var global Identifier) (usages: 2, declared: true) 
		    Binding(__join var global Identifier) (usages: 2, declared: true) 
		    Binding(__push var global Identifier) (usages: 6, declared: true) 
		    Binding(__hasOwnProperty var global Identifier) (usages: 11, declared: true) 
		    Binding(__propertyIsEnumerable var global Identifier) (usages: 2, declared: true) 
		    Binding(nonIndexNumericPropertyName var global Identifier) (usages: 2, declared: true) 
		    Binding(verifyProperty let global FunctionDeclaration) (usages: 5, declared: true) 
		    Binding(isConfigurable let global FunctionDeclaration) (usages: 4, declared: true) 
		    Binding(isEnumerable let global FunctionDeclaration) (usages: 4, declared: true) 
		    Binding(isSameValue let global FunctionDeclaration) (usages: 5, declared: true) 
		    Binding(isWritable let global FunctionDeclaration) (usages: 4, declared: true) 
		    Binding(verifyCallableProperty let global FunctionDeclaration) (usages: 2, declared: true) 
		    Binding(verifyEqualTo let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(verifyWritable let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(verifyNotWritable let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(verifyEnumerable let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(verifyNotEnumerable let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(verifyConfigurable let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(verifyNotConfigurable let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(verifyPrimordialProperty var global Identifier) (usages: 1, declared: true) 
		    Binding(verifyPrimordialCallableProperty var global Identifier) (usages: 1, declared: true) 
		    Binding(x let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(TestClass let global ClassDeclaration) (usages: 1, declared: true) 
		    Binding(hoistedVar var global Identifier) (usages: 1, declared: true) 
		    Binding(varInNestedBlocks let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(varShadowsParam let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(multipleVarSameName let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(funcVsVar let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(funcInBlock let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(varBeforeFunc let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(outerHoisting let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(varInForIn let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(varInForOf let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(varDestructuring let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(sloppyBlockFunc let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(varInLabeled let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(complexParam let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(usageBeforeDecl let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(catchParamShadow let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(captureCheck let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(someFunction let global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(Array var global Identifier) (usages: 3, declared: false) 
		    Binding(Object var global Identifier) (usages: 5, declared: false) 
		    Binding(Function var global Identifier) (usages: 4, declared: false) 
		    Binding(Math var global Identifier) (usages: 1, declared: false) 
		  Scope(1 FunctionDeclaration (parent: 0)
		    Binding(mustBeTrue var local Identifier) (usages: 3, declared: true) 
		    Binding(message var local Identifier) (usages: 4, declared: true) 
		  Scope(2 BlockStatement (parent: 1)
		    Binding(undefined var local Identifier) (usages: 1, declared: false) 
		  Scope(3 BlockStatement (parent: 2)
		  Scope(4 BlockStatement (parent: 2)
		  Scope(5 FunctionExpression (parent: 0)
		    Binding(a var local Identifier) (usages: 6, declared: true) 
		    Binding(b var local Identifier) (usages: 5, declared: true) 
		  Scope(6 BlockStatement (parent: 5)
		  Scope(7 BlockStatement (parent: 6)
		  Scope(8 FunctionExpression (parent: 0)
		    Binding(actual var local Identifier) (usages: 3, declared: true) 
		    Binding(expected var local Identifier) (usages: 3, declared: true) 
		    Binding(message var local Identifier) (usages: 7, declared: true) 
		  Scope(9 BlockStatement (parent: 8)
		    Binding(undefined var local Identifier) (usages: 1, declared: false) 
		  Scope(10 BlockStatement (parent: 9)
		  Scope(11 BlockStatement (parent: 10)
		  Scope(12 CatchClause (parent: 9)
		    Binding(error let local Identifier) (usages: 2, declared: true) 
		  Scope(13 BlockStatement (parent: 12)
		  Scope(14 BlockStatement (parent: 9)
		  Scope(15 BlockStatement (parent: 9)
		  Scope(16 FunctionExpression (parent: 0)
		    Binding(actual var local Identifier) (usages: 3, declared: true) 
		    Binding(unexpected var local Identifier) (usages: 3, declared: true) 
		    Binding(message var local Identifier) (usages: 6, declared: true) 
		  Scope(17 BlockStatement (parent: 16)
		    Binding(undefined var local Identifier) (usages: 1, declared: false) 
		  Scope(18 BlockStatement (parent: 17)
		  Scope(19 BlockStatement (parent: 17)
		  Scope(20 BlockStatement (parent: 17)
		  Scope(21 FunctionExpression (parent: 0)
		    Binding(expectedErrorConstructor var local Identifier) (usages: 4, declared: true) 
		    Binding(func var local Identifier) (usages: 3, declared: true) 
		    Binding(message var local Identifier) (usages: 11, declared: true) 
		  Scope(22 BlockStatement (parent: 21)
		    Binding(expectedName var local Identifier) (usages: 5, declared: true) 
		    Binding(actualName var local Identifier) (usages: 4, declared: true) 
		    Binding(undefined var local Identifier) (usages: 1, declared: false) 
		  Scope(23 BlockStatement (parent: 22)
		  Scope(24 BlockStatement (parent: 22)
		  Scope(25 BlockStatement (parent: 22)
		  Scope(26 BlockStatement (parent: 22)
		  Scope(27 CatchClause (parent: 22)
		    Binding(thrown let local Identifier) (usages: 5, declared: true) 
		  Scope(28 BlockStatement (parent: 27)
		  Scope(29 BlockStatement (parent: 28)
		  Scope(30 BlockStatement (parent: 28)
		  Scope(31 BlockStatement (parent: 30)
		  Scope(32 BlockStatement (parent: 30)
		  Scope(33 FunctionDeclaration (parent: 0)
		    Binding(value var local Identifier) (usages: 4, declared: true) 
		  Scope(34 BlockStatement (parent: 33)
		  Scope(35 FunctionExpression (parent: 0)
		    Binding(actual var local Identifier) (usages: 5, declared: true) 
		    Binding(expected var local Identifier) (usages: 5, declared: true) 
		    Binding(message var local Identifier) (usages: 10, declared: true) 
		  Scope(36 BlockStatement (parent: 35)
		    Binding(result var local Identifier) (usages: 2, declared: true) 
		    Binding(format var local Identifier) (usages: 3, declared: true) 
		    Binding(undefined var local Identifier) (usages: 1, declared: false) 
		  Scope(37 BlockStatement (parent: 36)
		  Scope(38 BlockStatement (parent: 36)
		  Scope(39 BlockStatement (parent: 36)
		  Scope(40 FunctionDeclaration (parent: 0)
		    Binding(a var local Identifier) (usages: 4, declared: true) 
		    Binding(b var local Identifier) (usages: 3, declared: true) 
		  Scope(41 BlockStatement (parent: 40)
		    Binding(i var local Identifier) (usages: 5, declared: true) 
		  Scope(42 BlockStatement (parent: 41)
		  Scope(43 ForStatement (parent: 41)
		  Scope(44 BlockStatement (parent: 43)
		  Scope(45 BlockStatement (parent: 44)
		  Scope(46 FunctionExpression (parent: 0)
		    Binding(arrayLike var local Identifier) (usages: 2, declared: true) 
		  Scope(47 BlockStatement (parent: 46)
		    Binding(Array var local Identifier) (usages: 1, declared: false) 
		    Binding(String var local Identifier) (usages: 1, declared: false) 
		  Scope(48 FunctionExpression (parent: 0)
		    Binding(formatIdentityFreeValue let local FunctionExpression) (usages: 1, declared: true) 
		    Binding(value var local Identifier) (usages: 9, declared: true) 
		  Scope(49 BlockStatement (parent: 48)
		  Scope(50 SwitchStatement (parent: 49)
		    Binding(JSON var local Identifier) (usages: 2, declared: false) 
		    Binding(Infinity var local Identifier) (usages: 1, declared: false) 
		    Binding(String var local Identifier) (usages: 1, declared: false) 
		  Scope(51 FunctionExpression (parent: 0)
		    Binding(value var local Identifier) (usages: 4, declared: true) 
		  Scope(52 BlockStatement (parent: 51)
		    Binding(basic var local Identifier) (usages: 3, declared: true) 
		  Scope(53 BlockStatement (parent: 52)
		    Binding(String var local Identifier) (usages: 1, declared: false) 
		  Scope(54 CatchClause (parent: 52)
		    Binding(err let local Identifier) (usages: 3, declared: true) 
		  Scope(55 BlockStatement (parent: 54)
		  Scope(56 BlockStatement (parent: 55)
		    Binding(Object var local Identifier) (usages: 1, declared: false) 
		  Scope(57 FunctionDeclaration (parent: 0)
		    Binding(message var local Identifier) (usages: 2, declared: true) 
		  Scope(58 BlockStatement (parent: 57)
		  Scope(59 FunctionExpression (parent: 0)
		  Scope(60 BlockStatement (parent: 59)
		  Scope(61 FunctionExpression (parent: 0)
		    Binding(message var local Identifier) (usages: 2, declared: true) 
		  Scope(62 BlockStatement (parent: 61)
		  Scope(63 FunctionDeclaration (parent: 0)
		  Scope(64 BlockStatement (parent: 63)
		  Scope(65 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 8, declared: true) 
		    Binding(name var local Identifier) (usages: 9, declared: true) 
		    Binding(desc var local Identifier) (usages: 26, declared: true) 
		    Binding(options var local Identifier) (usages: 3, declared: true) 
		    Binding(arguments var local FunctionDeclaration) (usages: 1, declared: true) 
		  Scope(66 BlockStatement (parent: 65)
		    Binding(originalDesc var local Identifier) (usages: 7, declared: true) 
		    Binding(nameStr var local Identifier) (usages: 8, declared: true) 
		    Binding(names var local Identifier) (usages: 9, declared: true) 
		    Binding(i var local Identifier) (usages: 10, declared: true) 
		    Binding(failures var local Identifier) (usages: 8, declared: true) 
		    Binding(String var local Identifier) (usages: 2, declared: false) 
		    Binding(undefined var local Identifier) (usages: 5, declared: false) 
		  Scope(67 BlockStatement (parent: 66)
		  Scope(68 ForStatement (parent: 66)
		  Scope(69 BlockStatement (parent: 68)
		  Scope(70 BlockStatement (parent: 66)
		  Scope(71 BlockStatement (parent: 70)
		  Scope(72 BlockStatement (parent: 70)
		  Scope(73 BlockStatement (parent: 66)
		  Scope(74 BlockStatement (parent: 73)
		  Scope(75 BlockStatement (parent: 66)
		  Scope(76 BlockStatement (parent: 75)
		  Scope(77 BlockStatement (parent: 66)
		  Scope(78 BlockStatement (parent: 77)
		  Scope(79 BlockStatement (parent: 66)
		  Scope(80 BlockStatement (parent: 66)
		  Scope(81 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 3, declared: true) 
		    Binding(name var local Identifier) (usages: 3, declared: true) 
		  Scope(82 BlockStatement (parent: 81)
		  Scope(83 BlockStatement (parent: 82)
		  Scope(84 CatchClause (parent: 82)
		    Binding(e let local Identifier) (usages: 3, declared: true) 
		  Scope(85 BlockStatement (parent: 84)
		    Binding(TypeError var local Identifier) (usages: 1, declared: false) 
		  Scope(86 BlockStatement (parent: 85)
		  Scope(87 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 4, declared: true) 
		    Binding(name var local Identifier) (usages: 5, declared: true) 
		  Scope(88 BlockStatement (parent: 87)
		    Binding(stringCheck var local Identifier) (usages: 4, declared: true) 
		    Binding(x var local Identifier) (usages: 2, declared: true) 
		  Scope(89 BlockStatement (parent: 88)
		  Scope(90 ForInStatement (parent: 89)
		  Scope(91 BlockStatement (parent: 90)
		  Scope(92 BlockStatement (parent: 91)
		  Scope(93 BlockStatement (parent: 88)
		  Scope(94 FunctionDeclaration (parent: 0)
		    Binding(a var local Identifier) (usages: 6, declared: true) 
		    Binding(b var local Identifier) (usages: 6, declared: true) 
		  Scope(95 BlockStatement (parent: 94)
		  Scope(96 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 8, declared: true) 
		    Binding(name var local Identifier) (usages: 8, declared: true) 
		    Binding(verifyProp var local Identifier) (usages: 2, declared: true) 
		    Binding(value var local Identifier) (usages: 2, declared: true) 
		    Binding(arguments var local FunctionDeclaration) (usages: 1, declared: true) 
		  Scope(97 BlockStatement (parent: 96)
		    Binding(unlikelyValue var local Identifier) (usages: 2, declared: true) 
		    Binding(newValue var local Identifier) (usages: 6, declared: true) 
		    Binding(hadValue var local Identifier) (usages: 2, declared: true) 
		    Binding(oldValue var local Identifier) (usages: 3, declared: true) 
		    Binding(writeSucceeded var local Identifier) (usages: 4, declared: true) 
		  Scope(98 BlockStatement (parent: 97)
		  Scope(99 BlockStatement (parent: 97)
		  Scope(100 CatchClause (parent: 97)
		    Binding(e let local Identifier) (usages: 3, declared: true) 
		  Scope(101 BlockStatement (parent: 100)
		    Binding(TypeError var local Identifier) (usages: 1, declared: false) 
		  Scope(102 BlockStatement (parent: 101)
		  Scope(103 BlockStatement (parent: 97)
		  Scope(104 BlockStatement (parent: 103)
		  Scope(105 BlockStatement (parent: 103)
		  Scope(106 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 3, declared: true) 
		    Binding(name var local Identifier) (usages: 7, declared: true) 
		    Binding(functionName var local Identifier) (usages: 5, declared: true) 
		    Binding(functionLength var local Identifier) (usages: 2, declared: true) 
		    Binding(desc var local Identifier) (usages: 9, declared: true) 
		    Binding(options var local Identifier) (usages: 4, declared: true) 
		  Scope(107 BlockStatement (parent: 106)
		    Binding(value var local Identifier) (usages: 6, declared: true) 
		    Binding(String var local Identifier) (usages: 1, declared: false) 
		    Binding(undefined var local Identifier) (usages: 2, declared: false) 
		  Scope(108 BlockStatement (parent: 107)
		  Scope(109 BlockStatement (parent: 107)
		  Scope(110 BlockStatement (parent: 107)
		  Scope(111 BlockStatement (parent: 110)
		  Scope(112 BlockStatement (parent: 110)
		  Scope(113 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 3, declared: true) 
		    Binding(name var local Identifier) (usages: 4, declared: true) 
		    Binding(value var local Identifier) (usages: 3, declared: true) 
		  Scope(114 BlockStatement (parent: 113)
		  Scope(115 BlockStatement (parent: 114)
		    Binding(String var local Identifier) (usages: 1, declared: false) 
		  Scope(116 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 3, declared: true) 
		    Binding(name var local Identifier) (usages: 5, declared: true) 
		    Binding(verifyProp var local Identifier) (usages: 3, declared: true) 
		    Binding(value var local Identifier) (usages: 2, declared: true) 
		  Scope(117 BlockStatement (parent: 116)
		  Scope(118 BlockStatement (parent: 117)
		    Binding(String var local Identifier) (usages: 1, declared: false) 
		  Scope(119 BlockStatement (parent: 117)
		    Binding(String var local Identifier) (usages: 1, declared: false) 
		  Scope(120 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 3, declared: true) 
		    Binding(name var local Identifier) (usages: 5, declared: true) 
		    Binding(verifyProp var local Identifier) (usages: 3, declared: true) 
		    Binding(value var local Identifier) (usages: 1, declared: true) 
		  Scope(121 BlockStatement (parent: 120)
		  Scope(122 BlockStatement (parent: 121)
		    Binding(String var local Identifier) (usages: 1, declared: false) 
		  Scope(123 BlockStatement (parent: 121)
		    Binding(String var local Identifier) (usages: 1, declared: false) 
		  Scope(124 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 3, declared: true) 
		    Binding(name var local Identifier) (usages: 5, declared: true) 
		  Scope(125 BlockStatement (parent: 124)
		    Binding(String var local Identifier) (usages: 2, declared: false) 
		  Scope(126 BlockStatement (parent: 125)
		  Scope(127 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 3, declared: true) 
		    Binding(name var local Identifier) (usages: 5, declared: true) 
		  Scope(128 BlockStatement (parent: 127)
		    Binding(String var local Identifier) (usages: 2, declared: false) 
		  Scope(129 BlockStatement (parent: 128)
		  Scope(130 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 3, declared: true) 
		    Binding(name var local Identifier) (usages: 5, declared: true) 
		  Scope(131 BlockStatement (parent: 130)
		    Binding(String var local Identifier) (usages: 2, declared: false) 
		  Scope(132 BlockStatement (parent: 131)
		  Scope(133 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 3, declared: true) 
		    Binding(name var local Identifier) (usages: 5, declared: true) 
		  Scope(134 BlockStatement (parent: 133)
		    Binding(String var local Identifier) (usages: 2, declared: false) 
		  Scope(135 BlockStatement (parent: 134)
		  Scope(136 FunctionDeclaration (parent: 0)
		    Binding(quix var local ObjectPattern) (usages: 1, declared: true) 
		  Scope(137 BlockStatement (parent: 136)
		    Binding(y let captured FunctionDeclaration) (usages: 1, declared: true) 
		  Scope(138 FunctionDeclaration (parent: 137)
		    Binding(arg var local Identifier) (usages: 1, declared: true) 
		  Scope(139 BlockStatement (parent: 138)
		  Scope(140 ClassDeclaration (parent: 0)
		    Binding(staticField var local Identifier) (usages: 1, declared: false) 
		    Binding(publicField var local Identifier) (usages: 1, declared: false) 
		  Scope(141 FunctionExpression (parent: 140)
		    Binding(name var local Identifier) (usages: 2, declared: true) 
		  Scope(142 BlockStatement (parent: 141)
		  Scope(143 FunctionExpression (parent: 140)
		  Scope(144 BlockStatement (parent: 143)
		  Scope(145 FunctionExpression (parent: 140)
		  Scope(146 BlockStatement (parent: 145)
		  Scope(147 FunctionExpression (parent: 140)
		    Binding(v var local Identifier) (usages: 2, declared: true) 
		  Scope(148 BlockStatement (parent: 147)
		  Scope(149 StaticBlock (parent: 140)
		    Binding(blockScoped let local Identifier) (usages: 1, declared: true) 
		  Scope(150 FunctionExpression (parent: 140)
		  Scope(151 BlockStatement (parent: 150)
		    Binding(functionScoped var local Identifier) (usages: 2, declared: true) 
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		  Scope(152 BlockStatement (parent: 151)
		    Binding(blockScoped let local Identifier) (usages: 1, declared: true) 
		  Scope(153 FunctionDeclaration (parent: 0)
		  Scope(154 BlockStatement (parent: 153)
		    Binding(hoistedFromIf var local Identifier) (usages: 2, declared: true) 
		    Binding(hoistedFromWhile var local Identifier) (usages: 2, declared: true) 
		    Binding(hoistedFromSwitch var local Identifier) (usages: 2, declared: true) 
		    Binding(hoistedFromTry var local Identifier) (usages: 1, declared: true) 
		    Binding(hoistedFromCatch var local Identifier) (usages: 1, declared: true) 
		    Binding(hoistedFromFinally var local Identifier) (usages: 1, declared: true) 
		    Binding(i var local Identifier) (usages: 3, declared: true) 
		    Binding(hoistedFromFor var local Identifier) (usages: 1, declared: true) 
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		  Scope(155 BlockStatement (parent: 154)
		  Scope(156 BlockStatement (parent: 154)
		  Scope(157 SwitchStatement (parent: 154)
		  Scope(158 BlockStatement (parent: 154)
		  Scope(159 CatchClause (parent: 154)
		    Binding(e let local Identifier) (usages: 1, declared: true) 
		  Scope(160 BlockStatement (parent: 159)
		  Scope(161 BlockStatement (parent: 154)
		  Scope(162 ForStatement (parent: 154)
		  Scope(163 BlockStatement (parent: 162)
		  Scope(164 FunctionDeclaration (parent: 0)
		    Binding(param1 var local Identifier) (usages: 1, declared: true) 
		    Binding(param2 var local Identifier) (usages: 1, declared: true) 
		  Scope(165 BlockStatement (parent: 164)
		    Binding(param1 var local Identifier) (usages: 2, declared: true) 
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		  Scope(166 FunctionDeclaration (parent: 0)
		  Scope(167 BlockStatement (parent: 166)
		    Binding(x var local Identifier) (usages: 3, declared: true) 
		    Binding(x var local Identifier) (usages: 0, declared: true) 
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		  Scope(168 BlockStatement (parent: 167)
		  Scope(169 FunctionDeclaration (parent: 0)
		  Scope(170 BlockStatement (parent: 169)
		    Binding(innerFunc var captured Identifier) (usages: 3, declared: true) 
		    Binding(innerFunc let local FunctionDeclaration) (usages: 0, declared: true) 
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		  Scope(171 FunctionDeclaration (parent: 170)
		  Scope(172 BlockStatement (parent: 171)
		  Scope(173 FunctionDeclaration (parent: 0)
		  Scope(174 BlockStatement (parent: 173)
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		    Binding(blockFunc var local Identifier) (usages: 1, declared: false) 
		  Scope(175 BlockStatement (parent: 174)
		    Binding(blockFunc let captured FunctionDeclaration) (usages: 1, declared: true) 
		  Scope(176 FunctionDeclaration (parent: 175)
		  Scope(177 BlockStatement (parent: 176)
		  Scope(178 FunctionDeclaration (parent: 0)
		  Scope(179 BlockStatement (parent: 178)
		    Binding(sameName var captured Identifier) (usages: 3, declared: true) 
		    Binding(sameName let local FunctionDeclaration) (usages: 0, declared: true) 
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		  Scope(180 FunctionDeclaration (parent: 179)
		  Scope(181 BlockStatement (parent: 180)
		  Scope(182 FunctionDeclaration (parent: 0)
		  Scope(183 BlockStatement (parent: 182)
		    Binding(innerFn let captured FunctionDeclaration) (usages: 2, declared: true) 
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		  Scope(184 FunctionDeclaration (parent: 183)
		  Scope(185 BlockStatement (parent: 184)
		  Scope(186 BlockStatement (parent: 183)
		    Binding(nestedBlock let captured FunctionDeclaration) (usages: 1, declared: true) 
		  Scope(187 FunctionDeclaration (parent: 186)
		  Scope(188 BlockStatement (parent: 187)
		  Scope(189 FunctionDeclaration (parent: 0)
		  Scope(190 BlockStatement (parent: 189)
		    Binding(key var local Identifier) (usages: 3, declared: true) 
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		  Scope(191 ForInStatement (parent: 190)
		  Scope(192 BlockStatement (parent: 191)
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		  Scope(193 FunctionDeclaration (parent: 0)
		  Scope(194 BlockStatement (parent: 193)
		    Binding(item var local Identifier) (usages: 3, declared: true) 
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		  Scope(195 ForOfStatement (parent: 194)
		  Scope(196 BlockStatement (parent: 195)
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		  Scope(197 FunctionDeclaration (parent: 0)
		  Scope(198 BlockStatement (parent: 197)
		    Binding(a var local ObjectPattern) (usages: 2, declared: true) 
		    Binding(renamed var local ObjectPattern) (usages: 2, declared: true) 
		    Binding(first var local ArrayPattern) (usages: 2, declared: true) 
		    Binding(second var local ArrayPattern) (usages: 2, declared: true) 
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		  Scope(199 FunctionDeclaration (parent: 0)
		  Scope(200 BlockStatement (parent: 199)
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		    Binding(blockHoisted var local Identifier) (usages: 1, declared: false) 
		  Scope(201 BlockStatement (parent: 200)
		    Binding(blockHoisted let captured FunctionDeclaration) (usages: 1, declared: true) 
		  Scope(202 FunctionDeclaration (parent: 201)
		  Scope(203 BlockStatement (parent: 202)
		  Scope(204 FunctionDeclaration (parent: 0)
		  Scope(205 BlockStatement (parent: 204)
		    Binding(i var local Identifier) (usages: 5, declared: true) 
		    Binding(j var local Identifier) (usages: 5, declared: true) 
		    Binding(outer var local Identifier) (usages: 2, declared: false) 
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		  Scope(206 ForStatement (parent: 205)
		  Scope(207 BlockStatement (parent: 206)
		    Binding(inner var local Identifier) (usages: 1, declared: false) 
		  Scope(208 ForStatement (parent: 207)
		  Scope(209 BlockStatement (parent: 208)
		  Scope(210 FunctionDeclaration (parent: 0)
		    Binding(defaultParam var local AssignmentPattern) (usages: 1, declared: true) 
		  Scope(211 FunctionExpression (parent: 210)
		  Scope(212 BlockStatement (parent: 211)
		    Binding(inDefault var local Identifier) (usages: 2, declared: true) 
		  Scope(213 BlockStatement (parent: 210)
		    Binding(inDefault var local Identifier) (usages: 2, declared: true) 
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		  Scope(214 FunctionDeclaration (parent: 0)
		  Scope(215 BlockStatement (parent: 214)
		    Binding(helper let captured FunctionDeclaration) (usages: 2, declared: true) 
		  Scope(216 FunctionDeclaration (parent: 215)
		  Scope(217 BlockStatement (parent: 216)
		  Scope(218 FunctionDeclaration (parent: 0)
		  Scope(219 BlockStatement (parent: 218)
		    Binding(e var local Identifier) (usages: 0, declared: true) 
		  Scope(220 BlockStatement (parent: 219)
		    Binding(Error var local Identifier) (usages: 1, declared: false) 
		  Scope(221 CatchClause (parent: 219)
		    Binding(e let local Identifier) (usages: 3, declared: true) 
		  Scope(222 BlockStatement (parent: 221)
		    Binding(console var local Identifier) (usages: 1, declared: false) 
		  Scope(223 FunctionDeclaration (parent: 0)
		  Scope(224 BlockStatement (parent: 223)
		    Binding(captured let captured Identifier) (usages: 2, declared: true) 
		  Scope(225 FunctionExpression (parent: 224)
		  Scope(226 BlockStatement (parent: 225)
		  Scope(227 FunctionDeclaration (parent: 0)
		    Binding(x var local ObjectPattern) (usages: 6, declared: true) 
		    Binding(y var local ObjectPattern) (usages: 3, declared: true) 
		  Scope(228 BlockStatement (parent: 227)
		  Scope(229 BlockStatement (parent: 228)
		    Binding(result const local Identifier) (usages: 2, declared: true) 
		"
	`);
});
