import * as path from "node:path";
import { expect, test } from "vitest";
import { parseScript } from "../src/parser.ts";
import {
	analyzeSourceAndRunSemanticAnalysis,
	debugSemanticProgram,
} from "../src/semantic-analysis.ts";
import { loadEntrypointAndRunSemanticAnalysis } from "../src/semantic-program.ts";

test("snapshot sema changes", () => {
	const fixturePath = path.join(import.meta.dirname, "./local/semantic-analysis.js");
	const semantic = loadEntrypointAndRunSemanticAnalysis(fixturePath, {
		entryGoal: "script",
	});

	expect(debugSemanticProgram(semantic).replaceAll(fixturePath, "<fixture>"))
		.toMatchInlineSnapshot(`
		"<fixture>
		  Scope(0 Program (parent: -1)
		    Binding(assert var global FunctionDeclaration) (usages: 34, declared: true) 
		    Binding(isPrimitive var global FunctionDeclaration) (usages: 3, declared: true) 
		    Binding(compareArray var global FunctionDeclaration) (usages: 4, declared: true) 
		    Binding(Test262Error var global FunctionDeclaration) (usages: 21, declared: true) 
		    Binding($DONOTEVALUATE var global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(__isArray var global Identifier) (usages: 2, declared: true) 
		    Binding(__defineProperty var global Identifier) (usages: 2, declared: true) 
		    Binding(__getOwnPropertyDescriptor var global Identifier) (usages: 8, declared: true) 
		    Binding(__getOwnPropertyNames var global Identifier) (usages: 2, declared: true) 
		    Binding(__join var global Identifier) (usages: 2, declared: true) 
		    Binding(__push var global Identifier) (usages: 6, declared: true) 
		    Binding(__hasOwnProperty var global Identifier) (usages: 11, declared: true) 
		    Binding(__propertyIsEnumerable var global Identifier) (usages: 2, declared: true) 
		    Binding(nonIndexNumericPropertyName var global Identifier) (usages: 2, declared: true) 
		    Binding(verifyProperty var global FunctionDeclaration) (usages: 5, declared: true) 
		    Binding(isConfigurable var global FunctionDeclaration) (usages: 4, declared: true) 
		    Binding(isEnumerable var global FunctionDeclaration) (usages: 4, declared: true) 
		    Binding(isSameValue var global FunctionDeclaration) (usages: 5, declared: true) 
		    Binding(isWritable var global FunctionDeclaration) (usages: 4, declared: true) 
		    Binding(verifyCallableProperty var global FunctionDeclaration) (usages: 2, declared: true) 
		    Binding(verifyEqualTo var global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(verifyWritable var global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(verifyNotWritable var global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(verifyEnumerable var global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(verifyNotEnumerable var global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(verifyConfigurable var global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(verifyNotConfigurable var global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(verifyPrimordialProperty var global Identifier) (usages: 1, declared: true) 
		    Binding(verifyPrimordialCallableProperty var global Identifier) (usages: 1, declared: true) 
		    Binding(x var global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(TestClass let global ClassDeclaration) (usages: 0, declared: true)\x20
		    Binding(varInNestedBlocks var global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(varShadowsParam var global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(multipleVarSameName var global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(funcVsVar var global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(funcInBlock var global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(varBeforeFunc var global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(outerHoisting var global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(varInForIn var global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(varInForOf var global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(varDestructuring var global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(sloppyBlockFunc var global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(varInLabeled var global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(complexParam var global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(usageBeforeDecl var global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(catchParamShadow var global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(captureCheck var global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(someFunction var global FunctionDeclaration) (usages: 1, declared: true) 
		    Binding(undefined var global Identifier) (usages: 12, declared: false) 
		    Binding(Array var global Identifier) (usages: 4, declared: false) 
		    Binding(String var global Identifier) (usages: 19, declared: false) 
		    Binding(JSON var global Identifier) (usages: 2, declared: false) 
		    Binding(Infinity var global Identifier) (usages: 1, declared: false) 
		    Binding(Object var global Identifier) (usages: 6, declared: false) 
		    Binding(Function var global Identifier) (usages: 4, declared: false) 
		    Binding(Math var global Identifier) (usages: 1, declared: false) 
		    Binding(TypeError var global Identifier) (usages: 2, declared: false) 
		    Binding(staticField var global Identifier) (usages: 1, declared: false) 
		    Binding(publicField var global Identifier) (usages: 1, declared: false) 
		    Binding(console var global Identifier) (usages: 17, declared: false) 
		    Binding(blockFunc var global Identifier) (usages: 1, declared: false) 
		    Binding(blockHoisted var global Identifier) (usages: 1, declared: false) 
		    Binding(outer var global Identifier) (usages: 2, declared: false) 
		    Binding(inner var global Identifier) (usages: 1, declared: false) 
		    Binding(Error var global Identifier) (usages: 1, declared: false) 
		  Scope(1 FunctionDeclaration (parent: 0)
		    Binding(mustBeTrue var local Identifier) (usages: 3, declared: true) 
		    Binding(message var local Identifier) (usages: 4, declared: true) 
		  Scope(2 BlockStatement (parent: 1)
		  Scope(3 BlockStatement (parent: 2)
		  Scope(4 BlockStatement (parent: 2)
		  Scope(5 FunctionExpression (parent: 0)
		    Binding(a var local Identifier) (usages: 6, declared: true) 
		    Binding(b var local Identifier) (usages: 5, declared: true) 
		  Scope(6 BlockStatement (parent: 5)
		  Scope(7 BlockStatement (parent: 6)
		  Scope(8 FunctionExpression (parent: 0)
		    Binding(actual var local Identifier) (usages: 3, declared: true) 
		    Binding(expected var local Identifier) (usages: 3, declared: true) 
		    Binding(message var local Identifier) (usages: 7, declared: true) 
		  Scope(9 BlockStatement (parent: 8)
		  Scope(10 BlockStatement (parent: 9)
		  Scope(11 BlockStatement (parent: 10)
		  Scope(12 CatchClause (parent: 9)
		    Binding(error let local Identifier) (usages: 2, declared: true) 
		  Scope(13 BlockStatement (parent: 12)
		  Scope(14 BlockStatement (parent: 9)
		  Scope(15 BlockStatement (parent: 9)
		  Scope(16 FunctionExpression (parent: 0)
		    Binding(actual var local Identifier) (usages: 3, declared: true) 
		    Binding(unexpected var local Identifier) (usages: 3, declared: true) 
		    Binding(message var local Identifier) (usages: 6, declared: true) 
		  Scope(17 BlockStatement (parent: 16)
		  Scope(18 BlockStatement (parent: 17)
		  Scope(19 BlockStatement (parent: 17)
		  Scope(20 BlockStatement (parent: 17)
		  Scope(21 FunctionExpression (parent: 0)
		    Binding(expectedErrorConstructor var local Identifier) (usages: 4, declared: true) 
		    Binding(func var local Identifier) (usages: 3, declared: true) 
		    Binding(message var local Identifier) (usages: 11, declared: true) 
		    Binding(expectedName var local Identifier) (usages: 5, declared: true) 
		    Binding(actualName var local Identifier) (usages: 4, declared: true) 
		  Scope(22 BlockStatement (parent: 21)
		  Scope(23 BlockStatement (parent: 22)
		  Scope(24 BlockStatement (parent: 22)
		  Scope(25 BlockStatement (parent: 22)
		  Scope(26 BlockStatement (parent: 22)
		  Scope(27 CatchClause (parent: 22)
		    Binding(thrown let local Identifier) (usages: 5, declared: true) 
		  Scope(28 BlockStatement (parent: 27)
		  Scope(29 BlockStatement (parent: 28)
		  Scope(30 BlockStatement (parent: 28)
		  Scope(31 BlockStatement (parent: 30)
		  Scope(32 BlockStatement (parent: 30)
		  Scope(33 FunctionDeclaration (parent: 0)
		    Binding(value var local Identifier) (usages: 4, declared: true) 
		  Scope(34 BlockStatement (parent: 33)
		  Scope(35 FunctionExpression (parent: 0)
		    Binding(actual var local Identifier) (usages: 5, declared: true) 
		    Binding(expected var local Identifier) (usages: 5, declared: true) 
		    Binding(message var local Identifier) (usages: 10, declared: true) 
		    Binding(result var local Identifier) (usages: 2, declared: true) 
		    Binding(format var local Identifier) (usages: 3, declared: true) 
		  Scope(36 BlockStatement (parent: 35)
		  Scope(37 BlockStatement (parent: 36)
		  Scope(38 BlockStatement (parent: 36)
		  Scope(39 BlockStatement (parent: 36)
		  Scope(40 FunctionDeclaration (parent: 0)
		    Binding(a var local Identifier) (usages: 4, declared: true) 
		    Binding(b var local Identifier) (usages: 3, declared: true) 
		    Binding(i var local Identifier) (usages: 5, declared: true) 
		  Scope(41 BlockStatement (parent: 40)
		  Scope(42 BlockStatement (parent: 41)
		  Scope(43 ForStatement (parent: 41)
		  Scope(44 BlockStatement (parent: 43)
		  Scope(45 BlockStatement (parent: 44)
		  Scope(46 FunctionExpression (parent: 0)
		    Binding(arrayLike var local Identifier) (usages: 2, declared: true) 
		  Scope(47 BlockStatement (parent: 46)
		  Scope(48 FunctionExpression (parent: 0)
		    Binding(formatIdentityFreeValue let local FunctionExpression) (usages: 1, declared: true) 
		    Binding(value var local Identifier) (usages: 9, declared: true) 
		  Scope(49 BlockStatement (parent: 48)
		  Scope(50 SwitchStatement (parent: 49)
		  Scope(51 FunctionExpression (parent: 0)
		    Binding(value var local Identifier) (usages: 4, declared: true) 
		    Binding(basic var local Identifier) (usages: 3, declared: true) 
		  Scope(52 BlockStatement (parent: 51)
		  Scope(53 BlockStatement (parent: 52)
		  Scope(54 CatchClause (parent: 52)
		    Binding(err let local Identifier) (usages: 3, declared: true) 
		  Scope(55 BlockStatement (parent: 54)
		  Scope(56 BlockStatement (parent: 55)
		  Scope(57 FunctionDeclaration (parent: 0)
		    Binding(message var local Identifier) (usages: 2, declared: true) 
		  Scope(58 BlockStatement (parent: 57)
		  Scope(59 FunctionExpression (parent: 0)
		  Scope(60 BlockStatement (parent: 59)
		  Scope(61 FunctionExpression (parent: 0)
		    Binding(message var local Identifier) (usages: 2, declared: true) 
		  Scope(62 BlockStatement (parent: 61)
		  Scope(63 FunctionDeclaration (parent: 0)
		  Scope(64 BlockStatement (parent: 63)
		  Scope(65 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 8, declared: true) 
		    Binding(name var local Identifier) (usages: 9, declared: true) 
		    Binding(desc var local Identifier) (usages: 26, declared: true) 
		    Binding(options var local Identifier) (usages: 3, declared: true) 
		    Binding(originalDesc var local Identifier) (usages: 7, declared: true) 
		    Binding(nameStr var local Identifier) (usages: 8, declared: true) 
		    Binding(names var local Identifier) (usages: 9, declared: true) 
		    Binding(i var local Identifier) (usages: 10, declared: true) 
		    Binding(failures var local Identifier) (usages: 8, declared: true) 
		    Binding(arguments var local FunctionDeclaration) (usages: 1, declared: true) 
		  Scope(66 BlockStatement (parent: 65)
		  Scope(67 BlockStatement (parent: 66)
		  Scope(68 ForStatement (parent: 66)
		  Scope(69 BlockStatement (parent: 68)
		  Scope(70 BlockStatement (parent: 66)
		  Scope(71 BlockStatement (parent: 70)
		  Scope(72 BlockStatement (parent: 70)
		  Scope(73 BlockStatement (parent: 66)
		  Scope(74 BlockStatement (parent: 73)
		  Scope(75 BlockStatement (parent: 66)
		  Scope(76 BlockStatement (parent: 75)
		  Scope(77 BlockStatement (parent: 66)
		  Scope(78 BlockStatement (parent: 77)
		  Scope(79 BlockStatement (parent: 66)
		  Scope(80 BlockStatement (parent: 66)
		  Scope(81 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 3, declared: true) 
		    Binding(name var local Identifier) (usages: 3, declared: true) 
		  Scope(82 BlockStatement (parent: 81)
		  Scope(83 BlockStatement (parent: 82)
		  Scope(84 CatchClause (parent: 82)
		    Binding(e let local Identifier) (usages: 3, declared: true) 
		  Scope(85 BlockStatement (parent: 84)
		  Scope(86 BlockStatement (parent: 85)
		  Scope(87 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 4, declared: true) 
		    Binding(name var local Identifier) (usages: 5, declared: true) 
		    Binding(stringCheck var local Identifier) (usages: 4, declared: true) 
		    Binding(x var local Identifier) (usages: 2, declared: true) 
		  Scope(88 BlockStatement (parent: 87)
		  Scope(89 BlockStatement (parent: 88)
		  Scope(90 ForInStatement (parent: 89)
		  Scope(91 BlockStatement (parent: 90)
		  Scope(92 BlockStatement (parent: 91)
		  Scope(93 BlockStatement (parent: 88)
		  Scope(94 FunctionDeclaration (parent: 0)
		    Binding(a var local Identifier) (usages: 6, declared: true) 
		    Binding(b var local Identifier) (usages: 6, declared: true) 
		  Scope(95 BlockStatement (parent: 94)
		  Scope(96 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 8, declared: true) 
		    Binding(name var local Identifier) (usages: 8, declared: true) 
		    Binding(verifyProp var local Identifier) (usages: 2, declared: true) 
		    Binding(value var local Identifier) (usages: 2, declared: true) 
		    Binding(unlikelyValue var local Identifier) (usages: 2, declared: true) 
		    Binding(newValue var local Identifier) (usages: 6, declared: true) 
		    Binding(hadValue var local Identifier) (usages: 2, declared: true) 
		    Binding(oldValue var local Identifier) (usages: 3, declared: true) 
		    Binding(writeSucceeded var local Identifier) (usages: 4, declared: true) 
		    Binding(arguments var local FunctionDeclaration) (usages: 1, declared: true) 
		  Scope(97 BlockStatement (parent: 96)
		  Scope(98 BlockStatement (parent: 97)
		  Scope(99 BlockStatement (parent: 97)
		  Scope(100 CatchClause (parent: 97)
		    Binding(e let local Identifier) (usages: 3, declared: true) 
		  Scope(101 BlockStatement (parent: 100)
		  Scope(102 BlockStatement (parent: 101)
		  Scope(103 BlockStatement (parent: 97)
		  Scope(104 BlockStatement (parent: 103)
		  Scope(105 BlockStatement (parent: 103)
		  Scope(106 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 3, declared: true) 
		    Binding(name var local Identifier) (usages: 7, declared: true) 
		    Binding(functionName var local Identifier) (usages: 5, declared: true) 
		    Binding(functionLength var local Identifier) (usages: 2, declared: true) 
		    Binding(desc var local Identifier) (usages: 9, declared: true) 
		    Binding(options var local Identifier) (usages: 4, declared: true) 
		    Binding(value var local Identifier) (usages: 6, declared: true) 
		  Scope(107 BlockStatement (parent: 106)
		  Scope(108 BlockStatement (parent: 107)
		  Scope(109 BlockStatement (parent: 107)
		  Scope(110 BlockStatement (parent: 107)
		  Scope(111 BlockStatement (parent: 110)
		  Scope(112 BlockStatement (parent: 110)
		  Scope(113 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 3, declared: true) 
		    Binding(name var local Identifier) (usages: 4, declared: true) 
		    Binding(value var local Identifier) (usages: 3, declared: true) 
		  Scope(114 BlockStatement (parent: 113)
		  Scope(115 BlockStatement (parent: 114)
		  Scope(116 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 3, declared: true) 
		    Binding(name var local Identifier) (usages: 5, declared: true) 
		    Binding(verifyProp var local Identifier) (usages: 3, declared: true) 
		    Binding(value var local Identifier) (usages: 2, declared: true) 
		  Scope(117 BlockStatement (parent: 116)
		  Scope(118 BlockStatement (parent: 117)
		  Scope(119 BlockStatement (parent: 117)
		  Scope(120 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 3, declared: true) 
		    Binding(name var local Identifier) (usages: 5, declared: true) 
		    Binding(verifyProp var local Identifier) (usages: 3, declared: true) 
		    Binding(value var local Identifier) (usages: 1, declared: true) 
		  Scope(121 BlockStatement (parent: 120)
		  Scope(122 BlockStatement (parent: 121)
		  Scope(123 BlockStatement (parent: 121)
		  Scope(124 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 3, declared: true) 
		    Binding(name var local Identifier) (usages: 5, declared: true) 
		  Scope(125 BlockStatement (parent: 124)
		  Scope(126 BlockStatement (parent: 125)
		  Scope(127 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 3, declared: true) 
		    Binding(name var local Identifier) (usages: 5, declared: true) 
		  Scope(128 BlockStatement (parent: 127)
		  Scope(129 BlockStatement (parent: 128)
		  Scope(130 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 3, declared: true) 
		    Binding(name var local Identifier) (usages: 5, declared: true) 
		  Scope(131 BlockStatement (parent: 130)
		  Scope(132 BlockStatement (parent: 131)
		  Scope(133 FunctionDeclaration (parent: 0)
		    Binding(obj var local Identifier) (usages: 3, declared: true) 
		    Binding(name var local Identifier) (usages: 5, declared: true) 
		  Scope(134 BlockStatement (parent: 133)
		  Scope(135 BlockStatement (parent: 134)
		  Scope(136 FunctionDeclaration (parent: 0)
		    Binding(quix var local ObjectPattern) (usages: 1, declared: true) 
		    Binding(y var captured FunctionDeclaration) (usages: 1, declared: true) 
		  Scope(137 BlockStatement (parent: 136)
		  Scope(138 FunctionDeclaration (parent: 137)
		    Binding(arg var local Identifier) (usages: 1, declared: true) 
		  Scope(139 BlockStatement (parent: 138)
		  Scope(140 ClassDeclaration (parent: 0)
		    Binding(TestClass const local Identifier) (usages: 1, declared: true)\x20
		  Scope(141 PropertyDefinition (parent: 140)
		  Scope(142 PropertyDefinition (parent: 140)
		  Scope(143 PropertyDefinition (parent: 140)
		  Scope(144 FunctionExpression (parent: 140)
		    Binding(name var local Identifier) (usages: 2, declared: true) 
		  Scope(145 BlockStatement (parent: 144)
		  Scope(146 FunctionExpression (parent: 140)
		  Scope(147 BlockStatement (parent: 146)
		  Scope(148 FunctionExpression (parent: 140)
		  Scope(149 BlockStatement (parent: 148)
		  Scope(150 FunctionExpression (parent: 140)
		    Binding(v var local Identifier) (usages: 2, declared: true) 
		  Scope(151 BlockStatement (parent: 150)
		  Scope(152 StaticBlock (parent: 140)
		    Binding(hoistedVar var local Identifier) (usages: 1, declared: true) 
		    Binding(blockScoped let local Identifier) (usages: 1, declared: true) 
		  Scope(153 FunctionExpression (parent: 140)
		    Binding(functionScoped var local Identifier) (usages: 2, declared: true) 
		  Scope(154 BlockStatement (parent: 153)
		  Scope(155 BlockStatement (parent: 154)
		    Binding(blockScoped let local Identifier) (usages: 1, declared: true) 
		  Scope(156 FunctionDeclaration (parent: 0)
		    Binding(hoistedFromIf var local Identifier) (usages: 2, declared: true) 
		    Binding(hoistedFromWhile var local Identifier) (usages: 2, declared: true) 
		    Binding(hoistedFromSwitch var local Identifier) (usages: 2, declared: true) 
		    Binding(hoistedFromTry var local Identifier) (usages: 1, declared: true) 
		    Binding(hoistedFromCatch var local Identifier) (usages: 1, declared: true) 
		    Binding(hoistedFromFinally var local Identifier) (usages: 1, declared: true) 
		    Binding(i var local Identifier) (usages: 3, declared: true) 
		    Binding(hoistedFromFor var local Identifier) (usages: 1, declared: true) 
		  Scope(157 BlockStatement (parent: 156)
		  Scope(158 BlockStatement (parent: 157)
		  Scope(159 BlockStatement (parent: 157)
		  Scope(160 SwitchStatement (parent: 157)
		  Scope(161 BlockStatement (parent: 157)
		  Scope(162 CatchClause (parent: 157)
		    Binding(e let local Identifier) (usages: 1, declared: true) 
		  Scope(163 BlockStatement (parent: 162)
		  Scope(164 BlockStatement (parent: 157)
		  Scope(165 ForStatement (parent: 157)
		  Scope(166 BlockStatement (parent: 165)
		  Scope(167 FunctionDeclaration (parent: 0)
		    Binding(param1 var local Identifier) (usages: 3, declared: true) 
		    Binding(param2 var local Identifier) (usages: 1, declared: true) 
		  Scope(168 BlockStatement (parent: 167)
		  Scope(169 FunctionDeclaration (parent: 0)
		    Binding(x var local Identifier) (usages: 3, declared: true) 
		  Scope(170 BlockStatement (parent: 169)
		  Scope(171 BlockStatement (parent: 170)
		  Scope(172 FunctionDeclaration (parent: 0)
		    Binding(innerFunc var captured Identifier) (usages: 3, declared: true) 
		  Scope(173 BlockStatement (parent: 172)
		  Scope(174 FunctionDeclaration (parent: 173)
		  Scope(175 BlockStatement (parent: 174)
		  Scope(176 FunctionDeclaration (parent: 0)
		  Scope(177 BlockStatement (parent: 176)
		  Scope(178 BlockStatement (parent: 177)
		    Binding(blockFunc let captured FunctionDeclaration) (usages: 1, declared: true) 
		  Scope(179 FunctionDeclaration (parent: 178)
		  Scope(180 BlockStatement (parent: 179)
		  Scope(181 FunctionDeclaration (parent: 0)
		    Binding(sameName var captured Identifier) (usages: 3, declared: true) 
		  Scope(182 BlockStatement (parent: 181)
		  Scope(183 FunctionDeclaration (parent: 182)
		  Scope(184 BlockStatement (parent: 183)
		  Scope(185 FunctionDeclaration (parent: 0)
		    Binding(innerFn var captured FunctionDeclaration) (usages: 2, declared: true) 
		  Scope(186 BlockStatement (parent: 185)
		  Scope(187 FunctionDeclaration (parent: 186)
		  Scope(188 BlockStatement (parent: 187)
		  Scope(189 BlockStatement (parent: 186)
		    Binding(nestedBlock let captured FunctionDeclaration) (usages: 1, declared: true) 
		  Scope(190 FunctionDeclaration (parent: 189)
		  Scope(191 BlockStatement (parent: 190)
		  Scope(192 FunctionDeclaration (parent: 0)
		    Binding(key var local Identifier) (usages: 3, declared: true) 
		  Scope(193 BlockStatement (parent: 192)
		  Scope(194 ForInStatement (parent: 193)
		  Scope(195 BlockStatement (parent: 194)
		  Scope(196 FunctionDeclaration (parent: 0)
		    Binding(item var local Identifier) (usages: 3, declared: true) 
		  Scope(197 BlockStatement (parent: 196)
		  Scope(198 ForOfStatement (parent: 197)
		  Scope(199 BlockStatement (parent: 198)
		  Scope(200 FunctionDeclaration (parent: 0)
		    Binding(a var local ObjectPattern) (usages: 2, declared: true) 
		    Binding(renamed var local ObjectPattern) (usages: 2, declared: true) 
		    Binding(first var local ArrayPattern) (usages: 2, declared: true) 
		    Binding(second var local ArrayPattern) (usages: 2, declared: true) 
		  Scope(201 BlockStatement (parent: 200)
		  Scope(202 FunctionDeclaration (parent: 0)
		  Scope(203 BlockStatement (parent: 202)
		  Scope(204 BlockStatement (parent: 203)
		    Binding(blockHoisted let captured FunctionDeclaration) (usages: 1, declared: true) 
		  Scope(205 FunctionDeclaration (parent: 204)
		  Scope(206 BlockStatement (parent: 205)
		  Scope(207 FunctionDeclaration (parent: 0)
		    Binding(i var local Identifier) (usages: 5, declared: true) 
		    Binding(j var local Identifier) (usages: 5, declared: true) 
		  Scope(208 BlockStatement (parent: 207)
		  Scope(209 ForStatement (parent: 208)
		  Scope(210 BlockStatement (parent: 209)
		  Scope(211 ForStatement (parent: 210)
		  Scope(212 BlockStatement (parent: 211)
		  Scope(213 FunctionDeclaration (parent: 0)
		    Binding(defaultParam var local AssignmentPattern) (usages: 1, declared: true) 
		  Scope(214 FunctionExpression (parent: 213)
		    Binding(inDefault var local Identifier) (usages: 2, declared: true) 
		  Scope(215 BlockStatement (parent: 214)
		  Scope(216 BlockStatement (parent: 213)
		    Binding(inDefault var local Identifier) (usages: 2, declared: true) 
		  Scope(217 FunctionDeclaration (parent: 0)
		    Binding(helper var captured FunctionDeclaration) (usages: 2, declared: true) 
		  Scope(218 BlockStatement (parent: 217)
		  Scope(219 FunctionDeclaration (parent: 218)
		  Scope(220 BlockStatement (parent: 219)
		  Scope(221 FunctionDeclaration (parent: 0)
		    Binding(e var local Identifier) (usages: 0, declared: true) 
		  Scope(222 BlockStatement (parent: 221)
		  Scope(223 BlockStatement (parent: 222)
		  Scope(224 CatchClause (parent: 222)
		    Binding(e let local Identifier) (usages: 3, declared: true) 
		  Scope(225 BlockStatement (parent: 224)
		  Scope(226 FunctionDeclaration (parent: 0)
		  Scope(227 BlockStatement (parent: 226)
		    Binding(captured let captured Identifier) (usages: 2, declared: true) 
		  Scope(228 FunctionExpression (parent: 227)
		  Scope(229 BlockStatement (parent: 228)
		  Scope(230 FunctionDeclaration (parent: 0)
		    Binding(x var local ObjectPattern) (usages: 6, declared: true) 
		    Binding(y var local ObjectPattern) (usages: 3, declared: true) 
		  Scope(231 BlockStatement (parent: 230)
		  Scope(232 BlockStatement (parent: 231)
		    Binding(result const local Identifier) (usages: 2, declared: true) 
		"
	`);
});

test.each([false, true])(
	"duplicate Script functions share one var binding (strict=%s)",
	(strict) => {
		const source = "function f(){ return 1 } function f(){ return 2 } f()";
		const semantic = analyzeSourceAndRunSemanticAnalysis(
			source,
			"duplicate.js",
			parseScript(source, { strict }),
		);
		const file = semantic.files[0]!;
		const declarations = file.ast.body.filter(
			(statement) => statement.type === "FunctionDeclaration",
		);
		const binding = file.nodeToBinding.get(declarations[0]!);

		expect(binding?.kind).toBe("var");
		expect(file.nodeToBinding.get(declarations[1]!)).toBe(binding);
		expect(
			file.scopes[0]!.bindings.filter((candidate) => candidate.name === "f"),
		).toEqual([binding]);
	},
);

test.each([false, true])(
	"duplicate function-body functions share one var binding (strict=%s)",
	(strict) => {
		const directive = strict ? '"use strict";' : "";
		const source = `${directive} function outer(){ function f(){ return 1 } function f(){ return 2 } return f() }`;
		const semantic = analyzeSourceAndRunSemanticAnalysis(
			source,
			"duplicate.js",
			parseScript(source, { strict: false }),
		);
		const file = semantic.files[0]!;
		const outer = file.ast.body.find(
			(statement) => statement.type === "FunctionDeclaration",
		);
		expect(outer?.type).toBe("FunctionDeclaration");
		const body = outer?.type === "FunctionDeclaration" ? outer.body : undefined;
		if (body?.type !== "BlockStatement") return;
		const declarations = body.body.filter(
			(statement) => statement.type === "FunctionDeclaration",
		);
		const binding = file.nodeToBinding.get(declarations[0]!);

		expect(binding?.kind).toBe("var");
		expect(file.nodeToBinding.get(declarations[1]!)).toBe(binding);
	},
);
