#include "compiler_wire.h"

#if MAL_EVAL

#include <stdio.h>
#include <stdlib.h>

// The baked compiler wire buffer (serialize-vm.ts format), generated by
// src/compiler-bake.ts before the runtime build. C23 `#embed` inlines the file from
// the content-addressed path supplied by the compiler command when the selected
// compiler supports it. Some C2x compilers accepted by the toolchain probe do
// not implement `#embed` yet, so keep a host-build fallback that reads the same
// content-addressed file at runtime.
#ifndef MAL_COMPILER_WIRE
#error "MAL_COMPILER_WIRE must name the cached compiler wire"
#endif

#ifdef __has_embed
#if __has_embed(MAL_COMPILER_WIRE)
#define MAL_COMPILER_WIRE_EMBEDDED 1
#endif
#endif

#if MAL_COMPILER_WIRE_EMBEDDED
static const u8 k_compiler_wire[] = {
#embed MAL_COMPILER_WIRE
};

const u8 *mal_compiler_wire_bytes(usize *len) {
    *len = sizeof(k_compiler_wire);
    return k_compiler_wire;
}
#else
const u8 *mal_compiler_wire_bytes(usize *len) {
    static u8 *buffer = nullptr;
    static usize buffer_len = 0;
    if (buffer != nullptr) {
        *len = buffer_len;
        return buffer;
    }

    FILE *file = fopen(MAL_COMPILER_WIRE, "rb");
    if (file == nullptr) {
        *len = 0;
        return nullptr;
    }
    if (fseek(file, 0, SEEK_END) != 0) {
        fclose(file);
        *len = 0;
        return nullptr;
    }
    long size = ftell(file);
    if (size < 0 || fseek(file, 0, SEEK_SET) != 0) {
        fclose(file);
        *len = 0;
        return nullptr;
    }

    u8 *next = malloc((usize) size);
    if (next == nullptr) {
        fclose(file);
        *len = 0;
        return nullptr;
    }
    usize read = fread(next, 1, (usize) size, file);
    fclose(file);
    if (read != (usize) size) {
        free(next);
        *len = 0;
        return nullptr;
    }

    buffer = next;
    buffer_len = (usize) size;
    *len = buffer_len;
    return buffer;
}
#endif

#else

// eval-disabled build (`engine.eval: false`): the 1.6 MB compiler is not embedded
// and compiler.malw need not exist. builtin_eval.c throws before ever asking for
// these bytes, so this stub only satisfies the linker.
const u8 *mal_compiler_wire_bytes(usize *len) {
    *len = 0;
    return nullptr;
}

#endif
