#include "compiler_wire.h"

// The baked compiler wire buffer (serialize-vm.ts format), generated by
// src/compiler-bake.ts before the cmake build. C23 `#embed` inlines the file's
// bytes; the path is resolved relative to this translation unit (runtime/src).
static const u8 k_compiler_wire[] = {
#embed "compiler.malw"
};

const u8 *mal_compiler_wire_bytes(usize *len) {
    *len = sizeof(k_compiler_wire);
    return k_compiler_wire;
}
