import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { format } from "oxfmt";

const sources: Readonly<Record<string, string>> = {
	"UnicodeData.txt": "2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c",
	"SpecialCasing.txt": "efc25faf19de21b92c1194c111c932e03d2a5eaf18194e33f1156e96de4c9588",
	"DerivedCoreProperties.txt":
		"24c7fed1195c482faaefd5c1e7eb821c5ee1fb6de07ecdbaa64b56a99da22c08",
	"CompositionExclusions.txt":
		"2f239196ef3b5b61db5cc476e9bd80f534d15aa1b74e1be1dea5d042a344c85f",
	"PropList.txt": "130dcddcaadaf071008bdfce1e7743e04fdfbc910886f017d9f9ac931d8c64dd",
};
const input = process.argv[2];
const output = process.argv[3];
if (!input || !output)
	throw new Error(
		"Usage: node scripts/generate-unicode-data.ts <Unicode-17.0.0-directory> <output-directory>",
	);
function rows(name: string): Array<Array<string>> {
	const bytes = readFileSync(resolve(input!, name));
	if (createHash("sha256").update(bytes).digest("hex") !== sources[name])
		throw new Error(`Unicode 17.0.0 source mismatch: ${name}`);
	return bytes
		.toString("utf8")
		.split(/\r?\n/)
		.map((line) => line.split("#")[0]!.trim())
		.filter(Boolean)
		.map((line) => line.split(";").map((field) => field.trim()));
}
const scalarList = (field: string) =>
	field === "" ? [] : field.split(/\s+/).map((cp) => Number.parseInt(cp, 16));
const lower = new Map<number, Array<number>>(),
	upper = new Map<number, Array<number>>();
const decomposition = new Map<
	number,
	{ values: Array<number>; compatibility: boolean }
>();
const classes = new Map<number, number>();
for (const row of rows("UnicodeData.txt")) {
	const cp = Number.parseInt(row[0]!, 16);
	if (row[12]) upper.set(cp, scalarList(row[12]));
	if (row[13]) lower.set(cp, scalarList(row[13]));
	if (row[3] !== "0") classes.set(cp, Number(row[3]));
	if (row[5])
		decomposition.set(cp, {
			values: scalarList(row[5].replace(/^<[^>]+>\s*/, "")),
			compatibility: row[5][0] === "<",
		});
}
const conditions = new Set<string>();
for (const row of rows("SpecialCasing.txt")) {
	if (row[4]) {
		conditions.add(row[4]);
		continue;
	}
	const cp = Number.parseInt(row[0]!, 16);
	lower.set(cp, scalarList(row[1]!));
	upper.set(cp, scalarList(row[3]!));
}
const expectedConditions = [
	"Final_Sigma",
	"lt After_Soft_Dotted",
	"lt More_Above",
	"lt",
	"tr",
	"az",
	"tr After_I",
	"az After_I",
	"tr Not_Before_Dot",
	"az Not_Before_Dot",
].sort();
if (JSON.stringify([...conditions].sort()) !== JSON.stringify(expectedConditions))
	throw new Error("Update the contextual case algorithms for changed UCD conditions");
const pool: Array<number> = [];
const mappings = (map: Map<number, Array<number>>) =>
	[...map]
		.filter(([cp, values]) => values.length !== 1 || values[0] !== cp)
		.sort(([a], [b]) => a - b)
		.flatMap(([cp, values]) => {
			const start = pool.length;
			pool.push(...values);
			return [cp, start, values.length];
		});
const data: Record<string, Array<number>> = {};
data.lower = mappings(lower);
data.upper = mappings(upper);
data.decomposition = [...decomposition]
	.sort(([a], [b]) => a - b)
	.flatMap(([cp, entry]) => {
		const start = pool.length;
		pool.push(...entry.values);
		return [cp, start, entry.values.length, Number(entry.compatibility)];
	});
data.classes = [...classes].sort(([a], [b]) => a - b).flat();
const excluded = new Set(
	rows("CompositionExclusions.txt").map((row) => Number.parseInt(row[0]!, 16)),
);
data.composition = [...decomposition]
	.filter(
		([cp, entry]) =>
			!entry.compatibility &&
			entry.values.length === 2 &&
			!excluded.has(cp) &&
			!classes.has(entry.values[0]!),
	)
	.map(([cp, entry]) => [entry.values[0]!, entry.values[1]!, cp])
	.sort((a, b) => a[0]! - b[0]! || a[1]! - b[1]!)
	.flat();
const propertyRows = [...rows("DerivedCoreProperties.txt"), ...rows("PropList.txt")];
for (const [name, property] of [
	["cased", "Cased"],
	["ignorable", "Case_Ignorable"],
	["softDotted", "Soft_Dotted"],
]) {
	const ranges = propertyRows
		.filter((row) => row[1] === property)
		.map((row) => {
			const pair = row[0]!.split("..");
			return [Number.parseInt(pair[0]!, 16), Number.parseInt(pair[1] ?? pair[0]!, 16)];
		})
		.sort((a, b) => a[0]! - b[0]!);
	data[name!] = ranges.flat();
}
data.pool = pool;
const provenance =
	"Generated by scripts/generate-unicode-data.ts from Unicode 17.0.0.\n// Unicode data license: runtime/vendor/unicode/LICENSE.txt.";
const ts = [`// ${provenance}`, 'export const UNICODE_VERSION = "17.0.0";'];
const c = [
	`// ${provenance}`,
	"#pragma once",
	'#include "defaults.h"',
	'#define MAL_UNICODE_VERSION "17.0.0"',
];
for (const [name, values] of Object.entries(data)) {
	// Packed text keeps generated data out of the compiler's per-element IR.
	ts.push(
		`export const unicode${name[0]!.toUpperCase()}${name.slice(1)} = new Uint32Array("${values.join(",")}".split(",").map(Number));`,
	);
	c.push(
		`static const u32 mal_unicode_${name.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`)}[] = {\n${Array.from({ length: Math.ceil(values.length / 16) }, (_, i) => `    ${values.slice(i * 16, i * 16 + 16).join(", ")},`).join("\n")}\n};`,
	);
}
mkdirSync(output, { recursive: true });
const formatted = await format("unicode-data.ts", `${ts.join("\n")}\n`, {
	useTabs: true,
	printWidth: 90,
});
if (formatted.errors.length !== 0) throw new Error("Could not format Unicode data");
writeFileSync(resolve(output, "unicode-data.ts"), formatted.code);
writeFileSync(resolve(output, "unicode_data.h"), `${c.join("\n")}\n`);
console.log(
	JSON.stringify(
		{
			version: "17.0.0",
			sources,
			entries: Object.fromEntries(
				Object.entries(data).map(([key, values]) => [key, values.length]),
			),
			output,
		},
		null,
		2,
	),
);
