import { createHash } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { compilerReplayCompilation } from "../bench/runtime-gap/compiler-replay-workload.mjs";
import {
	deserializeCompilerArtifact,
	serializeCompilerArtifact,
} from "../src/compiler/target/compiler-artifact-codec.ts";
import { lowerCoreCompilationToExecution } from "../src/compiler/target/lower-native-execution.ts";
import { lowerExecutionToProgramImage } from "../src/compiler/target/lower-native-program-image.ts";

const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const output = path.join(
	repositoryRoot,
	"bench/runtime-gap/fixtures/compiler-emitter-image.mjs",
);
mkdirSync(path.dirname(output), { recursive: true });
const image = deserializeCompilerArtifact(
	serializeCompilerArtifact(
		lowerExecutionToProgramImage(
			lowerCoreCompilationToExecution(compilerReplayCompilation, {
				reuseRegisters: true,
			}),
			false,
		),
	),
);
const payload = JSON.stringify(image);
const fingerprint = createHash("sha256").update(payload).digest("hex");
const source = `// Generated by scripts/generate-runtime-gap-compiler-fixture.mts.\nexport const compilerEmitterFixtureFingerprint = ${JSON.stringify(fingerprint)};\nexport const compilerEmitterImage = ${payload};\n`;
writeFileSync(output, source);
console.log(`${output} ${fingerprint} ${payload.length}`);
